### PR TITLE
[Feature] [Fix] Cleaning static

### PR DESCRIPTION
**Pull request by mfraezz**
Purpose
=======
Closes https://github.com/CenterForOpenScience/modular-file-renderer/issues/177
Closes https://github.com/CenterForOpenScience/modular-file-renderer/issues/176
Closes https://github.com/CenterForOpenScience/modular-file-renderer/issues/175

Changes
=======
* Put bootstrap css rules used by `codepygments` in `default.css`
* Removed unnecessary static files in `/pdb/`, `/pdf/`, `/svg/`, and `/tabular/`
* Remove reference to a deleted example file
    * It would never be used, MFR wouldn't get that far without a file being passed in:
```javascript
var DEFAULT_URL = '[some research paper by Mozilla].pdf';
[...]
var file = 'file' in params ? params.file : DEFAULT_URL;
```

Side Effects
=========
None, tested all filetypes that could be affected

CR Note
------------
[Commit 2]( https://github.com/mfraezz/modular-file-renderer/commit/d0ab31e63ca21abc4dbacae963d48f8bc9fcd85a ) is exclusively deletions, view other commits for modifications

### CODE REVIEW

**Comment by lyndsysimon** [comment]
Looks great. I've got some follow-up questions for you Steve, but they shouldn't be a part of this PR.

**Comment by lyndsysimon** [comment]
Oh! I almost forgot the gold star: :star2:

**Comment by icereval** [comment]
I'm struggling to understand why we would want to customize third party static assets? Third party plugins are meant to be drop in upgrades to the latest version with the fewest number of changes possible to have them integrated w/ the MFR.

This seems like a lot of work to maintain this practice going forward and also adds significant risk of an asset being missed or mistakenly removed.

If we are concerned about bloat in the code base we might investigate fixing this issue with a dependency manager like Bower, thus third party libraries are only brought into the picture on build and can remain separate.

Reviewing the referenced tickets they can be addressed with minimal changes such as removing the references to dependencies.

Please resubmit w/o asset deletions.

**Comment by mfraezz** [comment]
I'll close this for now, get a PR up for the pygments issues and add an issue about using a dependency manager.

**Pull request closed without merging**
