### PR TITLE
Feature/evernote (ENML) 

### PR DESCRIPTION
**Pull request by rdhyee**
Extension for ENML (Evernote Markup Language). 

These 3 PRs belong together:
* [Feature/evernote add-on by rdhyee · Pull Request #7043 · CenterForOpenScience/osf.io](https://github.com/CenterForOpenScience/osf.io/pull/7043)
* [Feature/evernote WB provider by rdhyee · Pull Request #206 · CenterForOpenScience/waterbutler](https://github.com/CenterForOpenScience/waterbutler/pull/206)
* [Feature/evernote (ENML) by rdhyee · Pull Request #249 · CenterForOpenScience/modular-file-renderer](https://github.com/CenterForOpenScience/modular-file-renderer/pull/249)

### CODE REVIEW

**Comment by felliott** [comment]
Supersedes #221.

**Comment by rdhyee** [comment]
Naming this a provider for ENML might be misleading since the output from WB is actually HTML to display.

**Comment by birdbrained** [comment]
@rdhyee I'm not sure what you mean when you say that you're getting html from wb. Is there another conversion happening somewhere?

**Comment by felliott** [comment]
D'oh! We're postponing work on this addon, and I meant to close this ticket.  @rdhyee's work has been archived in the repo on the [feature/evernote-addon](https://github.com/CenterForOpenScience/modular-file-renderer/tree/feature/evernote-addon) branch for future continuation.

**Pull request closed without merging**
