### PR TITLE
[Ready for Review][Feature]Markdown support

### PR DESCRIPTION
**Pull request by TomBaxter**
* Purpose
Render Markdown files to HTML
* Changes
New Extention "md"
Requires and utilizes python "markdown" library

### CODE REVIEW

**Comment by TomBaxter** [comment]
Is there any doc on how to test code end to end? Through a browser?

**Comment by mfraezz** [comment]
I updated the [contributing](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/CONTRIBUTING.rst#manual-local-testing) file with information about how to most easily render files locally. Let me know if you have any other questions.

**Comment by TomBaxter** [comment]
Thanks! That worked great. I was able to test through a browser.

**Comment by mfraezz** [comment]
:+1:

Just mark this as `[Ready for Review]` when you think it's complete, and someone on our team will review it.

**Comment by TomBaxter** [comment]
Is it safe to assume that the host for MFR is running node.js? If so, should I be testing against a particular version? Keep in mind I am very new to JavaScript, so not sure if my question makes sense. There is an MFR issue open requesting ComonMark support, preferably through markdown-js, I'm trying to give it a go.

**Comment by mfraezz** [comment]
No, the MFR uses a tornado server. If you're running the server locally you shouldn't need to do anything special for testing. 

And if you're referring to issue #142, this PR should resolve it.

**Comment by TomBaxter** [comment]
Understood, I'll leave this be for now then. Thanks.

**Comment by mfraezz** [comment]
Looks good to me. :star: 

The only thing I've found is that ~~strikethrough text~~, while supported with certain markdown renderers (e.g. Github's), isn't supported by the `markdown` library, but also isn't actually in the [markdown specification](http://daringfireball.net/projects/markdown/syntax). ¯\\\_(ツ)\_/¯

Moving this to CR2

**Comment by TomBaxter** [comment]
I added the markdown.Extension as shown in the release notes. It converts the the <> to &lt &gt  . Seems like a good solution. This assumes that when a user wants to render an .md or .markdown file that they are not expecting to see HTML code rendered but rather see the raw HTML.

**Comment by chrisseto** [comment]
LGTM, merging and deploying to staging

**Comment by felliott** [comment]
Hey @TomBaxter,

Just a heads up:  I've reverted this PR from develop and moved it to a new branch `feature/markdown-support`.  We have to resolve the issue of styling before its ready for merge (ditto .rst support).  @erinspace will be taking on that task later this sprint, which will involve signoff from our product and design folks here.  Once it's done, it'll get merged back into develop.

(Side note: the python-3.5 conversion was also reverted and moved into a new branch)

Cheers,
@felliott

**Pull request merged**
