### PR TITLE
Handle newer jasp files

### PR DESCRIPTION
**Pull request by RensDofferhoff**
## Purpose

[JASP](https://github.com/jasp-stats/jasp-desktop) files have been updated recently and could no longer be previewed on OSF.

## Changes

This PR removes some superfluous check that allow the file renderer to show both old and new jasp-files. A new test case is added for newer files.

### CODE REVIEW

**Comment by RensDofferhoff** [comment]
Any chance this could be merged quickly? 
Anything we need to add/change to comply?

**Comment by felliott** [comment]
Would there be any drawback to using the same approach as the [jamovi PR](#369 )? I'm prepping a release for that, and it seems like they might be similar.  I'd kinda like to keep the extra validation, since a lot of file types are renamed zip files.

I will test it locally with the jamovi fix (adding a check for the new manifest name), but is there anything else that I should be concerned about?  Thank you!

**Comment by felliott** [comment]
The exact fix didn't work since the format of the manifest changed.  I've adapted it a bit to still do some basic validation. This is merged into `develop` and I will cut a release early next week (post-new-years).

**Comment by felliott** [comment]
This has been released!

**Comment by JorisGoosen** [comment]
It works great, merci

**Pull request closed without merging**
