### PR TITLE
jamovi: update to accomodate new manifest location

### PR DESCRIPTION
**Pull request by jonathon-love**
## Purpose

the jamovi file format is placing the manifest in a different location (it turns out putting it at META-INF/MANIFEST.MF makes you the enemy of every email system).

## Changes

trivial changes, it now reads the new path, before falling back to the old path.

## Side effects

NO

## QA Notes

View a .omv file

## Deployment Notes

NA

### CODE REVIEW

**Comment by jonathon-love** [comment]
hi guys

this is 23 days old now. could you give me some idea what timeframe to expect?

with thanks

**Review by cslzchen — CHANGES_REQUESTED** [review]
Looks great! Thanks for contributing. Can you also update units tests for both old and new format.

* In [tests/extensions/jamovi/files](https://github.com/CenterForOpenScience/modular-file-renderer/tree/develop/tests/extensions/jamovi/files), add a new file `ok-new-manifest.omv` and rename the old `ok.mov` to `ok-old-manifest.omv`
* Update unit tests to cover both case in [here](https://github.com/CenterForOpenScience/modular-file-renderer/blob/develop/tests/extensions/jamovi/test_renderer.py#L70)

**Comment by cslzchen** [comment]
@jonathon-love, I am following up to see if you need anything else from us? In addition, @felliott is back and he will take care of merging this PR 🐧 after unit tests are updated.

**Comment by jonathon-love** [comment]
sorry, will get to this soon.

with thanks

**Comment by jonathon-love** [comment]
sorry for the delay on this one guys!

it's ready now.

with thanks

**Comment by felliott** [comment]
Looks good!  I've added a unittest for the old manifest format.  I'm prepping a release, it should go out next week.

**Comment by felliott** [comment]
This is merged into `develop`. I will cut a release early next week (post-new-years).

**Pull request closed without merging**
